image: trion/ng-cli-karma:latest

before_script:
    - cd webapp
    - npm install
    - npm run env

cache:
  paths:
    - node_modules/

stages:
  - build
  - test

job_build:
  stage: build
  script:
    - npm run build

job_lint:
  stage: test
  script:
    - npm run lint

job_karma:
  stage: test
  script:
    - npm run test
