image: trion/ng-cli-karma:latest

before_script:
    - echo start before_script...
    - cd webapp
    - npm install

cache:
  paths:
    - webapp/node_modules/

stages:
  - build
  - test

job_build:
  stage: build
  script:
    - echo start job_build...
    - npm run build

job_lint:
  stage: test
  script:
    - echo start job_lint...
    - npm run lint

job_karma:
  stage: test
  script:
    - echo start job_karma...
    - cd src
    - node dbserver.js & npm run test

job_e2e:
  stage: test
  script:
    - echo start job_e2e...
    - node ./node_modules/webdriver-manager/ update
    - cd src
    - node dbserver.js & npm run e2e
